In [14]:
import numpy as np

pr_point =[4,8,2,3,2]

rec_point=[0.25,0.5,0.5,0.75,1]
pr_ref=[3,2,4,5,2,1,5,2,4,2]
rec_ref=[0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1]
pr_point_corrected=[0] * (10)

ind=0
for r in range(len(rec_point)):
    for j in range(ind, len(rec_ref)):
        if rec_ref[j] <= rec_point[r]:
            ind += 1
            pr_point_corrected[ind-1] = pr_point[r]
print(pr_point_corrected )
    
    


[4, 4, 8, 8, 8, 3, 3, 2, 2, 2]


In [11]:
x= np.array([2,3,1,8,4,9,10])
np.where(x>4)

(array([3, 5, 6]),)

In [19]:
pr_point =np.array([4,8,2,3,2])

rec_point=np.array([0.25,0.5,0.5,0.75,1])
pr_ref=np.array([3,2,4,5,2,1,5,2,4,2])
rec_ref=np.array([0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1])
pr_point_corrected=[0] * (10)

tot=0
for r in range(len(rec_point)):
    ind=np.where(rec_ref <= rec_point[r])
    tot=ind[0][]
    print(ind[0])
    for x in ind[0]:
        pr_point_corrected[x]=pr_point[r]
print(pr_point_corrected )    

[0 1]
[0 1 2 3 4]
[0 1 2 3 4]
[0 1 2 3 4 5 6]
[0 1 2 3 4 5 6 7 8 9]
[2, 2, 2, 2, 2, 2, 2, 2, 2, 2]
